/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommunicationCreateNestedManyWithoutContactsInput } from "./CommunicationCreateNestedManyWithoutContactsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { LeadCreateNestedManyWithoutContactsInput } from "./LeadCreateNestedManyWithoutContactsInput";

@InputType()
class ContactCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommunicationCreateNestedManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => CommunicationCreateNestedManyWithoutContactsInput)
  @IsOptional()
  @Field(() => CommunicationCreateNestedManyWithoutContactsInput, {
    nullable: true,
  })
  communications?: CommunicationCreateNestedManyWithoutContactsInput;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LeadCreateNestedManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => LeadCreateNestedManyWithoutContactsInput)
  @IsOptional()
  @Field(() => LeadCreateNestedManyWithoutContactsInput, {
    nullable: true,
  })
  leads?: LeadCreateNestedManyWithoutContactsInput;
}

export { ContactCreateInput as ContactCreateInput };
